eth:
  outputs:
    ci:
      account: RCEXDQX-VAB00589
      database: CI_CD
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      role: ACCOUNTADMIN
      schema: CI_CD_ETH
      threads: 1
      type: snowflake
      user: RONYJESLIN130
      warehouse: COMPUTE_WH  
  target: ci